# Generated by Django 4.0.3 on 2022-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('info', models.CharField(max_length=255)),
                ('auctionstart', models.DateTimeField()),
                ('auctionend', models.DateTimeField()),
            ],
            options={
                'db_table': 'auction',
                'managed': False,
            },
        ),
    ]
