# Generated by Django 4.0.3 on 2022-03-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionBid',
            fields=[
                ('bidno', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('bidtime', models.DateTimeField()),
            ],
            options={
                'db_table': 'auction_bid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('itemname', models.CharField(max_length=255)),
                ('itemspecs', models.CharField(max_length=700)),
                ('floorprice', models.FloatField()),
                ('sellprice', models.FloatField()),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
    ]
