# Generated by Django 3.2.12 on 2022-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auctionbid_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeid', models.AutoField(primary_key=True, serialize=False)),
                ('storename', models.CharField(max_length=255)),
                ('storedesc', models.CharField(max_length=700)),
            ],
            options={
                'db_table': 'store',
                'managed': False,
            },
        ),
    ]
