# Generated by Django 4.0.3 on 2022-04-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_boodleuser_store_userfavorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userfavorites',
        ),
    ]
