# Generated by Django 3.2.12 on 2022-05-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_userfavorites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boodleuser',
        ),
    ]
